### ISSUE TITLE
Create AsyncStorage ClientStorage

### ISSUE THREAD

**Issue by tchock** [Hypheme/harmonized.js#10]

**Comment by tchock** [comment]
@JohannesMerz I would recommend to outsource this to a separate repository.
In this repo only widely used parts should be included. IndexedDb should be way more common, because of the web platform, so we should only include IndexedDb in 0.2.

**Comment by JohannesMerz** [comment]
@tchock i agree

**Comment by tchock** [comment]
Ok, will close this then
