### ISSUE TITLE
Base Transporter - get item status

### ISSUE THREAD

**Issue by tchock** [Hypheme/harmonized.js#2]
Get the current sync status like "in progress" like so:

transporter/clientStorage.create/update/remove/delete()
    .then(response =>{…});
response = {
    status: ‚success/pending‘, // is it done or still in queue
    inProgress: BEING_DELETED, // zusammengefasste transporter action (action des letzten queue eintrags denke ich), ‚EXISTENT/DELETED‘ wenn die queue leer ist (wenn alles abgearbeitet wurde und der status nich pending ist)
    data: ‚server response‘,
}

**Comment by JohannesMerz** [comment]
i'll close this because there will be smth much bigger coming... ;P
